### ISSUE TITLE
Bug: Demo Does Not Work

### ISSUE THREAD

**Issue by kookma** [Telumire/FontManager#1]
### Describe the bug

Seems the external core cannot be found!

### Steps to reproduce

Open the demo link

### Platforms

Desktop

### Browsers

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Telumire** [comment]
Yes this is because I repurposed my domain name "telumire.be", as a result this caused several of my wikis depending on this url to break.. I updated the wiki and changed the url, thanks for letting me know @kookma :)

- The external file version can now also be found here: https://telumire.github.io/FontManager
- I uploaded a standalone version here: https://telumire.github.io/FontManager/fontmanager-standalone.html
